import { FC } from 'react'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { SWRProvider } from '@/swr'

import { ColorSchemeScript, Container, MantineProvider } from '@mantine/core'
import { NavigationProgress } from '@mantine/nprogress'
import { Notifications } from '@mantine/notifications'

import { ProviderStore } from '@/store'
import { ProviderProps } from '@/common'

import { theme } from '@/styles/theme'
import '@mantine/core/styles.css'
import '@mantine/notifications/styles.css'
import '@/styles/global.scss'

const montserrat = Montserrat({ subsets: ['latin', 'cyrillic'] })

export const metadata: Metadata = {
  metadataBase: new URL('https://acme.com'),
  icons: '/d.png',
  title: 'Next App',
  description: 'Generated by create next app',
  openGraph: {
    title: 'Create Next App',
    description: 'Generated by create next app',
    url: 'https://nextjs.org',
    images: ['/d.png']
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Create Next App',
    description: 'Generated by create next app',
    site: 'https://nextjs.org',
    images: ['/d.png']
  }
}

const RootLayout: FC<ProviderProps> = ({ children }) => {
  return (
    <html lang="ru">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={montserrat.className}>
        <MantineProvider theme={theme}>
          <NavigationProgress />
          <Notifications position="bottom-left" />
          <SWRProvider>
            <ProviderStore>
              <Container size={'xl'} style={{ padding: 0 }}>
                {children}
              </Container>
            </ProviderStore>
          </SWRProvider>
        </MantineProvider>
      </body>
    </html>
  )
}

export default RootLayout
